upmc-enterprises/elasticsearch-operator

- pkg/processor/processor.go
Fixes #19 
Updated code so that the Elasticsearch data containers are created using the calculated base image to allow custom images to be used when specified in the cluster manifest.
> Fix bug regarding the use of the base image

- Makefile
- util/k8sutil/k8sutil.go
The watching of TPR was broken when removing `kubectl proxy`.  This makes sure the controller only looks at it's own namespace for deployments. A later PR needs to happen to make the controller work across any namespace.
> Namespace watch

- pkg/k8sutil/k8sutil.go
- pkg/processor/processor.go
- pkg/snapshot/scheduler.go
The snapshot url was trying to reach an incorect service url.
**Error**
```
[elasticsearch-operator-1974566318-c2qnx] time="2017-07-03T11:33:10Z"
level=error msg="Error attempting to create snapshot: Put 
https://elasticsearch:9200/_snapshot/elasticsnapshots99/snapshot_2017-07-03-11-33-10?wait_for_completion=true: 
dial tcp 100.67.80.146:9200: getsockopt: connection refused"
```
> fix the snapshot service url

- pkg/k8sutil/k8sutil.go
This prevents data nodes to be scheduled on the same node
> Add in Pod anti-affinity 

- README.md
- pkg/processor/processor.go
- pkg/spec/cluster.go
The use case is: non AWS environments like bare metal or, as in my case, other cloud provider without something similar to EBS. The ability to provide a storage class is a great more on flexibility without disturbing other configurations.
f.e. using it with GlusterFS 
```yaml
apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
name: es-suchen
namespace: suchen
spec:
client-node-replicas: 1
master-node-replicas: 1
data-node-replicas: 3
elastic-search-image: upmcenterprises/docker-elasticsearch-kubernetes:5.3.1_3
zones: []
data-volume-size: 2Gi
java-options: "-Xms256m -Xmx256m"
storage:
storage-class: distributed
```
for storage class:
```yaml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
name: distributed
provisioner: kubernetes.io/glusterfs …
```
> Storage Class as Option

- example/controller.yaml
Somehow indentation & values got a bit jumbled
```
error: error validating "example/controller.yaml": error validating data: [found invalid field readinessProbe for v1.ContainerPort, found invalid field livenessProbe for v1.ContainerPort]; if you choose to ignore these errors, turn validation off with --validate=false
```
```The Deployment "elasticsearch-operator" is invalid:
* spec.template.spec.containers[0].livenessProbe.httpGet.port: Invalid value: "8000": must contain at least one letter or number (a-z, 0-9)
* spec.template.spec.containers[0].readinessProbe.httpGet.port: Invalid value: "8000": must contain at least one letter or number (a-z, 0-9)
```
Thanks for the awesome project!
> Fix deployment example

- pkg/k8sutil/deployments.go
- pkg/k8sutil/k8sutil.go
Enable `readinessProbe` and `livenessProbe` for:  es data, es master es clients, kibana and cerebro
> create http probe for elasticsearch

- README.md
- charts/elasticsearch/values.yaml
- cmd/operator/main.go
- example/example-es-cluster-hostpath.yaml
- example/example-es-cluster-minikube.yaml
- example/example-es-cluster-rook.yaml
- example/example-es-cluster.yaml
Kibana image is moved to the oficial image, elasticsearch image depends on https://github.com/upmc-enterprises/docker-elasticsearch-kubernetes/pull/6
> Update elasticsearch and kibana to version 6.1.3

- pkg/apis/elasticsearchoperator/v1/cluster.go
- pkg/k8sutil/deployments.go
- pkg/k8sutil/k8sutil.go
- pkg/k8sutil/storage.go
- pkg/processor/processor.go
The function was using the hardcoded example-elasticsearch cluster name
> Fix PVC selection to enable update of VolumeReclaimPolicy of PV

- pkg/k8sutil/deployments.go
- pkg/k8sutil/k8sutil.go
- pkg/processor/processor.go
kibana and cerebro deployments fail with `use-ssl=false` since the certificates are missing.
> fixed kibana/cerebro deployments with use-ssl=false

- example/example-es-cluster-gke.yaml
Should probably remove the snapshot section until this can be merged:
https://github.com/upmc-enterprises/elasticsearch-operator/pull/209
> GKE compatible example cluster

- pkg/k8sutil/services.go
- pkg/processor/processor.go
The goal of this PR is to create the kibana/cerebro mgmt services only when the related images are specified in the configuration.
> create kibana/cerebro mgmt services only when needed

- README.md
- pkg/apis/elasticsearchoperator/v1/cluster.go
- pkg/processor/processor.go
- pkg/snapshot/scheduler.go
Allows for passing a repo type to the cronjob to support GCS repositories.
Depends on https://github.com/upmc-enterprises/elasticsearch-cron/pull/6
> Support for GCS Snapshots

- cmd/operator/main.go
- pkg/controller/controller.go
- pkg/k8sutil/daemonsets.go
- pkg/k8sutil/k8sutil.go
This PR addresses #219 by adding a command line flag specifying the namespace that the sysctl init daemonset should be deployed into. The default value for the flag is the default namespace which matches the current behavior. Users that want to deploy into a different namespace can do so by passing the namespace as an argument to operator.
> Make namespace of sysctl init daemonset configurable

- pkg/apis/elasticsearchoperator/v1/cluster.go
- pkg/k8sutil/deployments.go
- pkg/k8sutil/k8sutil.go
- pkg/k8sutil/k8sutil_test.go
- pkg/processor/processor.go
This PR allows each service to have an optional serviceAccountName. Helpful when setting up PodSecurityPolcies and granting permissions around.
Allows the user to set an optional serviceAcccountName for any of the
services. Elasticsearch, Kibana and Cerebro, defaults to none if not
set.
> Add serviceAcccountName option for each service

- pkg/k8sutil/daemonsets.go
The init daemonset is Linux specific.  Add a nodeSelector to limit it to only run on Linux nodes.
> Add nodeSelector to init daemonset so it only runs on Linux.

- pkg/apis/elasticsearchoperator/v1/cluster.go
- pkg/processor/processor.go
- pkg/snapshot/scheduler.go
This PR should solve [this issue](https://github.com/upmc-enterprises/elasticsearch-cron/issues/7) on es-cron to integrate option for S3 user credentials based backup for Snapshot. The bool flag ```--use-repo-auth``` will enable/disable this functionality (default: ```false```) as per user input. 
[Accompanying PR](https://github.com/upmc-enterprises/elasticsearch-cron/pull/8) in es-cron has been filed. The go tests for ```processer.go``` are passing.
> Added S3 user credentials functionality to Snapshots

- pkg/elasticsearchutil/elasticsearchutil.go
- pkg/elasticsearchutil/elasticsearchutil_test.go
- pkg/k8sutil/k8sutil.go
- pkg/k8sutil/pod.go
- pkg/processor/processor.go
This PR solves issue #105
We implemented scale up and scale down of master elasticsearch master nodes. 
**Scale up**:
We react on updated master pods. As soon as they are ready the `discovery.zen.minimum_master_nodes` setting is increased to `number_of_ready_master_pods / 2 + 1`.
**Scale down**:
Scale down is detected by a watch on the CRD elasticseach events, which reduce the number of master nodes. Reacting to scale down is critical because without adapting the `discovery.zen.minimum_master_nodes` setting, the quorum could be lost without the option to regain it.
> Adjust minimum master nodes dynamically

- example/example-es-cluster-minikube.yaml
- pkg/apis/elasticsearchoperator/v1/cluster.go
- pkg/k8sutil/deployments.go
- pkg/k8sutil/k8sutil.go
- pkg/k8sutil/k8sutil_test.go
- pkg/processor/processor.go
Adds support for specifying an optional `image-pull-policy` for each image in the cluster spec (ES/Kibana and Cerebro).
I've updated the minikube example to show how this works.
Validation looks to be handled by the underlying k8s core API (via `PullPolicy`)
> Support imagePullPolicy for image dependencies

- example/example-es-cluster-minikube.yaml
Was testing out the minikube deployment and couldn't apply the raw file with:
```
❯ kubectl create -f https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/example/example-es-cluster-minikube.yaml
error: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
```
Just a minor correction on the yaml.
> correct spacing on minikube manifest

- README.md
- pkg/apis/elasticsearchoperator/v1/cluster.go
- pkg/k8sutil/storage.go
- pkg/processor/processor.go
Allows "encryption" as a configurable in the clusterspec.yml for storageclass creation (defaults to true)
Eg:
```
storage:
type: gp2
storage-class-provisioner: kubernetes.io/aws-ebs
encrypted: "true"
```
> Allow encryption as a configurable for storageclass creation

- Makefile
Signed-off-by: Steve Sloka <slokas@vmware.com>
> Add 'devpreq' action to Makefile to setup local machine to run operator
