Makefile, cmd/operator/main.go, example/controller.yaml, example/example-es-cluster.json, pkg/controller/controller.go, pkg/processor/processor.go, pkg/snapshot/scheduler.go, pkg/spec/cluster.go
=> Fix bugs with scheduler / Refactor

Makefile, README.md, example/controller.yaml, example/example-es-cluster-minikube.json, example/example-es-cluster.json, pkg/processor/processor.go, pkg/spec/cluster.go, util/k8sutil/k8sutil.go
=> Enable minikube

pkg/snapshot/scheduler.go
=> Fixed broken snapshot url

pkg/snapshot/scheduler.go
This is part of #25, the previous PR only fixed the snapshot url, this fixes creating the correct snapshot repository.
=> Fixed url for creating snapshot repository

pkg/processor/processor.go, pkg/snapshot/scheduler.go
I missed authentication for CreateSnapshotRepository.
Also added ?wait_for_completion=true on the create snapshot. I found that if the backups happened to soon it would fail because the previous call was still running.  Also added additional logs
=> Missed authentication for CreateSnapshotRepository

example/controller.yaml
I tested this rules on my cluster getting successful deployments of operator, master and nodes
=> Provide rbac rules for elasticsearch operator

.travis.yml, README.md, example/example-es-cluster-minikube.json, pkg/k8sutil/k8sutil.go, pkg/processor/processor.go, pkg/spec/cluster.go
=> Enable support for specifying statsd host for instrumentation

example/example-es-cluster.json, pkg/k8sutil/k8sutil.go, pkg/processor/processor.go, pkg/spec/cluster.go
=> Add abilitty to specify NETWORK_HOST

README.md, cmd/operator/main.go, example/example-es-cluster-minikube.json, pkg/controller/controller.go, pkg/k8sutil/k8sutil.go, pkg/processor/processor.go, pkg/snapshot/scheduler.go, pkg/spec/cluster.go
The operator now works in any namespace and snapshots to s3 are now using CronJob in k8s 1.6+
=> Operate in any namespace / Update to use CronJob

Makefile, cmd/operator/main.go, example/controller.yaml, pkg/k8sutil/certs.go
- Fixes #74 where truststore.jks was not created correcting causing searchguard to break
- Bump version
=> Resolved issue where truststore.jks

README.md, example/controller.yaml
=> Updated rbac rules

example/example-es-cluster.json
=> Added networkhost to example cluster

example/example-es-cluster-minikube.json, example/example-es-cluster.json
Feedback from @djschny from #82 
// Fixes #82
=> Switched logic for network host

pkg/k8sutil/deployments.go, pkg/k8sutil/k8sutil.go, pkg/processor/processor.go, pkg/spec/cluster.go
=> Masters now have persistent data utilizing Statefulsets

example/example-es-cluster-azure.json
=> Added sample azure acs example

README.md, example/example-es-cluster.json, pkg/k8sutil/deployments.go, pkg/k8sutil/k8sutil.go, pkg/processor/processor.go, pkg/spec/cluster.go
=> Added support for deploying Kibana automatically

README.md, example/example-es-cluster-minikube.yaml, pkg/k8sutil/storage.go, pkg/processor/processor.go, pkg/spec/cluster.go
=> Allow VolumeReclaimPolicy to be configurable

example/example-es-cluster-hostpath.yaml, example/hostpath-sc.yaml
Add example host path storage class and sample cluster so that volumes can be provisioned with only host volumes. 
// #126
=> Add example hostpath provisioner

README.md, pkg/apis/elasticsearchoperator/v1/cluster.go, pkg/processor/processor.go
=> Added parameter to allow secrets to be kept if a cluster is deleted

charts/elasticsearch-operator/templates/rbac.yaml, charts/elasticsearch-operator/values.yaml, charts/elasticsearch/templates/cluster.yaml, charts/elasticsearch/values.yaml
I've tested this with my Kubernets v1.9.1 cluster. Working fine so far.
=> Fix helm charts to just work as described in README (with K8S 1.9)

example/example-es-cluster-minikube.yaml, pkg/controller/controller.go, pkg/k8sutil/daemonsets.go
Need to make namespace configurable
=> Implemented daemonset to properly configure nodes

README.md, charts/elasticsearch/Chart.yaml, charts/elasticsearch/values.yaml, charts/index.yaml, example/example-es-cluster-hostpath.yaml, example/example-es-cluster-minikube.yaml, example/example-es-cluster-rook.yaml, example/example-es-cluster.yaml, pkg/controller/controller.go, pkg/k8sutil/daemonsets.go, pkg/k8sutil/k8sutil.go, pkg/k8sutil/services.go, pkg/processor/processor.go
Create svc for kibana and cerebro
Use the same image version for kibana and es
=> Create kibana/cerebro service

Makefile, example/controller.yaml
Signed-off-by: Steve Sloka <steves@heptio.com>
=> Bump controller version

pkg/k8sutil/deployments.go
As title, fix the Kibana disable SSL bug [#199](https://github.com/upmc-enterprises/elasticsearch-operator/issues/199)
=> Fix #199 Readiness/Liveness probe of kibana not respecting use-ssl=false

charts/elasticsearch/templates/cluster.yaml, charts/elasticsearch/values.yaml
add the support to disable ssl when installing ElasticSearch cluster by helm
=> Support disable ssl when installing ElasticSearch cluster by helm

.travis.yml, hack/image_push.sh
Builds a `:master` tag on each push to master branch. 
Signed-off-by: Steve Sloka <steves@heptio.com>
=> Master branch builds

pkg/k8sutil/deployments.go, pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go, pkg/processor/processor.go
- Do not build certs and do not mount them if use-ssl = false
=> Fix #192 ssl certs

Makefile, example/controller.yaml
Signed-off-by: Steve Sloka <steve@stevesloka.com>
=> Bump version

pkg/processor/processor.go
Fixes #216 
Signed-off-by: Steve Sloka <steve@stevesloka.com>
=> Fix check on delete cluster looking at UseSSL pointer

Makefile, cmd/operator/main.go, example/controller.yaml
Signed-off-by: Steve Sloka <steves@heptio.com>
=> Release 0.2.0

pkg/apis/elasticsearchoperator/v1/cluster.go
Just rectifying some (presumably) copy/paste typos.
=> Fix typos.

cmd/operator/main.go, pkg/k8sutil/daemonsets.go, pkg/k8sutil/deployments.go, pkg/k8sutil/k8sutil.go, pkg/processor/processor.go
Fixes #139 by allowing the busy box image to be specified via args. Also remove deprecated init container via annotations.
=> Allow busybox image to be specified

cmd/operator/main.go, pkg/controller/controller.go, pkg/k8sutil/k8sutil.go
=> add flag to make init daemonset optional

charts/elasticsearch/templates/cluster.yaml, charts/elasticsearch/values.yaml, example/example-es-cluster-azure.yaml, example/example-es-cluster-gke.yaml, pkg/apis/elasticsearchoperator/v1/cluster.go
Links to: https://github.com/upmc-enterprises/elasticsearch-cron/pull/9/files
=> Support Azure snapshots to blob storage

pkg/processor/processor.go
avoids crash mentioned in #267
(do not know if this is a fix)
=> Fix slice panic

pkg/processor/processor.go
Reverts upmc-enterprises/elasticsearch-operator#268
=> Revert "Fix slice panic"

pkg/k8sutil/daemonsets.go, pkg/k8sutil/k8sutil.go
Signed-off-by: Steve Sloka <steve@stevesloka.com>
=> Fix daemonset logging

Dockerfile, Makefile, cmd/operator/main.go
Signed-off-by: Steve Sloka <slokas@vmware.com>
=> Release v0.3.0

pkg/processor/processor.go
The pod label selector logic did not account for the possibility of other pods in the cluster having label "component=**something**" where "**something**" might be less than 14 characters long, or the label "component=**something14charlong**" which might belong to some pod not related to elasticsearch.
Adding a length check and prefix check so that only labels of the type "component=elasticsearch-*" would be considered seems to prevent the operator from crashing.
=> Added pod label length check and prefix check

README.md, example/example-es-cluster-azure.yaml, example/example-es-cluster-gke.yaml, example/example-es-cluster-hostpath.yaml, example/example-es-cluster-ibm.yaml, example/example-es-cluster-minikube.yaml, example/example-es-cluster-rook.yaml, example/example-es-cluster.yaml, pkg/apis/elasticsearchoperator/v1/cluster.go, pkg/processor/processor.go
With large data volume sizes, a lot of free space on master nodes is wasted.
=> Add support for master volume size

Makefile, cmd/operator/main.go, example/controller.yaml
Signed-off-by: Steve Sloka <slokas@vmware.com>
=> Release v0.4.0
